const { SlashCommandBuilder } = require('@discordjs/builders')
const utilities = require('../utilities.js')

module.exports = {
    AoE: [
        "Yes.",
        "No.",
        "I need food.",
        "Somebody pass the wood.",
        "Gold please.",
        "Gimme some stone.",
        "*Whimper*",
        "Your attempts are futile.",
        "*Group cheer*",
        "Hey, I'm in your town.",
        "*Group groan*",
        "Join me!",
        "I don't think so.",
        "Start the game already!",
        "Who's the man?",
        "Attack them now!",
        "*Low laugh*",
        "I am weak, please don't kill me!",
        "*High pitched laugh*",
        "I just got some... satisfaction!",
        "Hey, nice town!",
        "We will NOT tolerate this behavior.",
        "Get out!",
        "Dad gum!",
        "Aw, yeah!",
        "Yes.",
        "No.",
        "Food please.",
        "Wood please.",
        "Gold please.",
        "Stone please.",
        "Ahh!",
        "All hail, king of the losers!",
        "Ooh!",
        "I'll beat you back to Age of Empires.",
        "(Herb laugh)",
        "Ah! Being rushed.",
        "Sure, blame it on your ISP.",
        "Start the game already!",
        "Don't point that thing at me!",
        "Enemy sighted",
        "It is good to be the king.",
        "Monk! I need a monk!",
        "Long time, no siege.",
        "My granny could scrap better than that.",
        "Nice town, I'll take it.",
        "Quit touching me!",
        "Raiding party!",
        "Dadgum.",
        "Eh, smite me.",
        "The wonder, the wonder, the... no!",
        "You played two hours to die like this?",
        "Yeah, well, you should see the other guy.",
        "Roggan.",
        "Wololo.",
        "Attack an enemy now.",
        "Cease creating extra villagers.",
        "Create extra villagers.",
        "Build a navy.",
        "Stop building a navy.",
        "Wait for my signal to attack.",
        "Build a wonder.",
        "Give me your extra resources.",
        "(Ally sound)",
        "(Enemy sound)",
        "(Neutral sound)",
        "What age are you in?",
        "Yes.",
        "No.",
        "Food please.",
        "Wood please.",
        "Gold please.",
        "Do you have extra resources?",
        "Aww",
        "Meet here",
        "Oooh",
        "Are you ready?",
        "(Laugh)",
        "I need help",
        "Sure, blame it on your firewall.",
        "Start the game already",
        "Attack now",
        "Build a wonder",
        "I have extra wood",
        "I have extra food",
        "I have extra gold",
        "You're my hero",
        "I'm scouting",
        "Whatever",
        "Oh, you let a girl beat you",
        "Are we there yet?",
        "Voted off",
        "Ouch, that had to hurt",
        "What happened to the stone?",
        "Throw things at me",
        "(Scream)",
        "Wololo.",
        "You're very brave",
        "Turn back now",
        "I feel less fighting",
        "Give up now",
        "Coward",
        "Did I mention that I am a god now?",
        "Not a wise decision but a decision nonetheless",
        "What do I gotta do to get some food around here",
        "I need some back-up",
        "Fire in the hole",
        "What a baby",
        "I wish he would stop doing that",
        "Ahh what a foolish decision",
        "Ahh you are such a fool",
        "Yes.",
        "No.",
        "I need food.",
        "I need wood.",
        "I need coin.",
        "Do you have extra resources.",
        "I have extra food.",
        "I have extra wood.",
        "I have extra coin.",
        "Meet here.",
        "Are you ready.",
        "I need help.",
        "Attack now.",
        "Upgrade your trade route.",
        "Wololo.",
        "I'm in your base, killing your dudes.",
        "Check in your wallet. That's me on the dollar bill.",
        "I believe that makes me your daddy.",
        "El-Oh-El, I am R-Oh-Tee-Eff-El. (Laugh out Loud, I am Rolling on the Floor Laughing.)",
        "Aren't you becoming quite the little problem.",
        "(Laughter)",
        "This will give me cred, street cred.",
        "Hey, shut your pie hole.",
        "I'll take that trade.",
        "You sit on the computer all day playing. You know nothing of hard life.",
        "Really. Such a noob.",
        "Ask not for whom the timer ticks. It ticks for thee.",
        "(Alternate laughter)",
        "Check in your pocket. The quarter is me, too.",
        "Where is my mother.",
        "(Charge bugle call)",
        "Believe it, little boy.",
        "Zing."
    ],
    data: new SlashCommandBuilder()
        .setName('aoe')
        .setDescription('Age of Empires taunter'),
    async execute(interaction) {
        taunt = utilities.choose(this.AoE)
        await interaction.reply(taunt)
    },
};