const { SlashCommandBuilder } = require('@discordjs/builders')
const {choose} = require("../utilities");

module.exports = {
    lines: [
        "Welcome to the Bread bank. We sell bread, we sell loafs. We got bread on deck, bread on the floor. TOASTED, RO-",
        "Shut the f\\*\\*\\* up. Listen, I just need a Baguette and a Brioche.",
        "We don't have either of those, you can get the gluten-free white bread or the potato bread-",
        "What the f\\*\\*\\* is gluten?! Take that s\\*\\*\\* out!",
        "It's gluten-free.",
        "I don't CARE if it's free.",
        "Swear on your f\\*\\*\\*ing Y E E Z Y S, if you wanna fight, we gon' fight.",
        "You tryna' be on WORLDSTAR?",
        "What, you gonna record it?",
        "Ye, I got my dollar store camera ON.",
        "What's the f\\*\\*\\*ing situætion?",
        "What the f\\*\\*\\* do you want?",
        "I'm the mother f\\*\\*\\*ing M A N A G E R",
        "At the bread store?",
        "B R E A D",
        "Tell him to take, the motherf\\*\\*\\*in' gluten, OUT THE BREAD.",
        "I'ma need you to shut that bulls\\*\\*\\* up chief. We can't take s\\*\\*\\* out the bread.",
        "Why put it in the first place?! I know y'all smoking that Pack.",
        "We got crackers, no gluten.",
        "f\\*\\*\\* crackers!!",
        "It's gluten free. Do you want the gluten or nah?",
        "Hell no. You Better take the gluten out that damn s\\*\\*\\*",
        "Look, we've got whole wheat, gluten free, texas toast, gluten free, TORTILLA-",
        "f\\*\\*\\* all that. What B\\*\\*\\*\\* A\\*\\* country are y'all from... where they got this Bulls\\*\\*\\* at?!",
        "Florida.",
        "I knew it.",
        "Look, you can either take this YeasT, or i'm calling the police.",
        "I'm going W E A S T .",
        "Nah, don't call the police, I got a warrant...",
        "Honestly, f\\*\\*\\* y'all! I ain't never seen nobody act like this over no bread",
        "What the f\\*\\*\\* are you sayin'?!",
        "All I'm saying is f\\*\\*\\* y'all's bread, f\\*\\*\\* the gluten, and f\\*\\*\\* them crackers.",
        "The crackers don't have gluten-",
        "I'll take those.",
        "Okay that's gonna be 5-",
        "Nah, f\\*\\*\\* that, I ain't payin'!",
        "Welcome to the bread bank we sell bread, we sell loaves we sell-- d\\*\\*\\* how that s\\*\\*\\* go again?",
        "Shut that s\\*\\*\\*! I'm here for the M A N A G E R",
        "Manager? It's my first day on the job.",
        "No s\\*\\*\\*. I ain't talkin' about you.",
        "I manage this bread tho.",
        "B\\*\\*\\*\\*, you can manage this a\\*\\* beatin'",
        "Anyways you tryna buy some bread?",
        "Why would I come here to buy some d\\*\\*\\* bread?",
        "B\\*\\*\\*\\* do it look like we sell movie tickets?",
        "I didn't come here for this dry a\\*\\* gluten",
        "We don't sell gluten either",
        "Yes you do",
        "What type of bread is that?",
        "You can't be that stupid",
        "It's my second day on the job",
        "No it's not",
        "It's my third day on the job",
        "Go get the manager",
        "We got seeabatta on sale",
        "What?",
        "Seeabatta",
        "It's ciabatta",
        "Didn't you hear what I just said? Goofball",
        "Ay what's good? I need a seeabatta with extra gluten",
        "We don't sell gluten",
        "D\\*\\*\\* they really hire just anybody to work here",
        "I'm getting out of here once I sell these NFTs",
        "You're lost",
        "Stop the cap, goofy a\\*\\* hyuck hycuk b\\*\\*\\*\\*",
        "What did you say?",
        "Dawg I know you ain't working at the d\\*\\*\\* bread bank",
        "I'm volunteering",
        "Oh you getting the slave wage",
        "He doing an internship at the bread bank",
        "I'm sick",
        "Come on man it's temporary",
        "I just seent yo a\\*\\* over at McDonald's",
        "You runnin' shifts back to back?",
        "I just robbed a gas station though",
        "You need to rob a library and go read a book",
        "Look I'm going to the back",
        "Yo are you wearing Bape",
        "Oh S\\*\\*\\*!",
        "Yea b\\*\\*\\*\\* that's custom",
        "That's clean",
        "D\\*\\*\\*, you the only b\\*\\*\\*\\* in the world with that ugly a\\*\\* fit on",
        "Are you kidding?",
        "Wait a minute, he got on the Vlon Nikes",
        "Cost me 10k, I'm F I N A N C I A L",
        "Oh he dripped out",
        "No he's not",
        "Talk to me when you get your swag up",
        "tAlK To me WhEN yoU-- Shut the h\\*\\*\\* up! Whoever told you to buy that s\\*\\*\\*, you need to leave them alone",
        "D\\*\\*\\*",
        "You still got them weak a\\*\\* yeezys on, f\\*\\*\\* out my life",
        "Oof",
        "You could have all the bread in the world and you still couldn't f\\*\\*\\* with me",
        "Nah",
        "Look I'm just here to talk to the manager",
        "This ain't gamestop if you here to play games",
        "I'll give you $30,0000 just to stfu man",
        "Somebody call for the M A N A G E R?",
        "Yes",
        "Why are you wearing a Gucci bucket hat?",
        "Why you worried about it?",
        "You ain't rockin' the s\\*\\*\\*, I'll tell you that",
        "Broke mfs telling me what I can't rock, ain't no way",
        "Why you got on Bape?",
        "You coming at me mad cuz your pockets low",
        "You could have all the bread in the world and your b\\*\\*\\*\\* a\\*\\* still couldn't f\\*\\*\\* with me",
        "I already said that",
        "So you tryna buy some bread? We doing negative percentage discounts",
        "What type of Krusty Krab s\\*\\*\\* is that?",
        "F\\*\\*\\* up Lil Bow Wow, you came up off a scratch off ticket",
        "D\\*\\*\\*",
        "It wasn't scratch off dawg it was a lottery ticket",
        "Lottery Drawing, L, L, Lottery Drawing-- B\\*\\*\\* I don't care, get your broke a\\*\\* back to work",
        "Work for them measly a\\*\\* funds? Measles f\\*\\*\\*in paychecks, I'll be aight",
        "Dummy, I'll snatch them goofy a\\*\\* Vlone shoes off your feet",
        "Bro got on the Halloween Town Low Tops",
        "Why you buy them h\\*\\*\\*?",
        "Your destiny is plain, Soon you will die alone",
        "Oh my God, You're not Vlone",
        "I got 16 Ferraris, I can 't even park them b\\*\\*\\*\\*es",
        "You can park in my driveway",
        "All that paper and no h\\*\\*\\*, couldn't be me",
        "Yes it could",
        "You don't understand the minutiae that comes with having this amount of B R E A D",
        "Only reason you came in this b\\*\\*\\*\\* was to flex the poverty tax",
        "Look if the bread was in your hands you'd be talking different",
        "Homeless people could give you money, It don't mean you take it",
        "Tf does that mean?",
        "He just be talkin'",
        "You a b\\*\\*\\*\\* for taking the jackpot",
        "Shut ya mouth, the lip gotta stop",
        "Buddy you came in here talking s\\*\\*\\*, You the one that lipped off",
        "Look I just need to get my seeabatta",
        "All I seen is broke activity",
        "That's real familiar, huh?",
        "Ay bruh can I get that 30k now?",
        "F\\*\\*\\* up dummy, I got Goyard bags to purchase, I'm out this b\\*\\*\\*\\*",
        "Man I coulda doordashed this s\\*\\*\\*. B\\*\\*\\*\\*es wasting my time"
    ],
    data: new SlashCommandBuilder()
        .setName('breadbank')
        .setDescription('Prints a random breadbank line.'),
    async execute(interaction) {
        await interaction.reply(`||${choose(this.lines)}||`)
    }
};